- name: "ensure apache2 is installed"
  apt:
    pkg: apache2
- name: Copiar web estática
  template:
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: "Copiar fichero de configuración y reiniciar el servicio"
  copy:
    src: etc/apache2/ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar apache2

- name: "ensure Apache2 service is running and enabled"
  service:
    name: apache2
    state: started
    enabled: yes
