- name: Activar bit de forward
  sysctl: 
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Configuración de las interfaces de red de router
  template:
    src: router-interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Reiniciar maquina
  reboot:
