- hosts: all
  become: true
  roles:
   - role: common

- hosts: routers
  become: true
  roles:
   - role: router

- hosts: clientes       
  become: true
  roles:
   - role: cliente 

- hosts: cliente       
  become: true
  roles:
   - role: web 
