- name: Configuración de las interfaces de red de cliente
  template:
    src: cliente-interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: "0644"

- name: Reiniciar máquina
  reboot:
